Repository davidsaulrodriguez/project-purple-planet, pull requests merged in 2021-02, with the labels that each got.

#1 WIP Created models for database
  models/board.js
  models/task.js
  models/user.js
Labels: enhancement

#10 Add Login and Signup pages
  views/login.handlebars
  views/signup.handlebars
Labels: front end, high priority

#12 Tested API routes with Postman
  app.js
  models/task.js
  routes/board-api-routes.js
  routes/task-api-routes.js
Labels: back end, enhancement, high priority

#14 🚧 UI landing page
  gulpfile.js
  src/assets/css/style.css
  src/assets/imgs/logo.svg
  src/assets/scss/style.scss
  views/index.handlebars
  views/layouts/main.handlebars
  views/partials/footer.handlebars
Labels: enhancement, front end, high priority

#20 Updated HTML Routes
  routes/html-routes.js
  src/assets/js/boards.js
  views/boards.handlebars
  views/layouts/main.handlebars
  views/tasks.handlebars
Labels: back end, enhancement, front end, high priority

#23 Hot fix docs and footer
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  SLC.md
  views/partials/footer.handlebars
Labels: documentation, front end

#24 removed unnecessary links
  views/partials/navLoggedIn.handlebars
Labels: front end

#25 UI login and signup fixes
  src/assets/scss/style.scss
  views/login.handlebars
  views/signup.handlebars
Labels: front end

#26 add user dash with working add/delete functions
  routes/html-routes.js
  src/assets/js/home.js
  src/assets/js/main.js
  views/boards.handlebars
  views/home.handlebars
Labels: back end, front end, high priority

#28 update task pages with add & delete functionality
  src/assets/js/tasks.js
  views/home.handlebars
  views/tasks.handlebars
Labels: enhancement, front end, high priority

#29 Heroku Deployment 🤞🏾
  .sequelizerc
  config/config.js
  config/config.json
  config/db.js
  models/index.js
  package.json
Labels: back end, high priority

#33 Display tasks on mobile devices
  views/tasks.handlebars
Labels: front end, high priority
